[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver"
version_provider = "scm"
update_changelog_on_bump = true
changelog_incremental = true
version_files = [
  "package.json:\"version\"",
  "src-tauri/tauri.conf.json:\"version\"",
  "src-tauri/Cargo.toml:^version"
]

[tool.commitizen.customize]
change_type_map = {"feat" = "Added", "fix" = "Fixed", "docs" = "Documentation"}
